blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    # http://localhost:8000/blog?page=1  进入博客列表,默认进入第一页
    path('', views.blog_list, name = 'blog_list'),
    # http://localhost:8000/blog/博客的id值  进入博客详情页面
    path('<int:blog_pk>', views.blog_detail, name = 'blog_detail'),
    # http://localhost:8000/blog/type/博客分类的id 按照博客分类对博客进行分类
    path('type/<int:blog_type_pk>', views.blogs_with_type, name = 'blogs_with_type'),
    # http://localhost:8000/blog/date/年/月 按照年月对博客进行归档
    path('date/<int:year>/<int:month>', views.blogs_with_date, name = 'blogs_with_date'),
]

mysite/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('user/', include('user.urls', namespace='user')),
    # path('signin/', views.sign_in, name='sign_in'),
    # path('signup/', views.sign_up, name='sign_up'),   
    path('comment/', include('comment.urls', namespace='comment')),  
    path('likes/', include('likes.urls', namespace='likes')),
]
# ckeditor富文本编辑器访问图片指定路径
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('signin/', views.sign_in, name='sign_in'),
    path('signup/', views.sign_up, name='sign_up'),
    path('signout/', views.sign_out, name='sign_out'),
    path('user_info/', views.user_info, name='user_info'),
    path('nickname_change/', views.nickname_change, name='nickname_change'),
    path('bind_email/', views.bind_email, name='bind_email'),
    path('send_verification_code/', views.send_verification_code, name='send_verification_code'),
]

blog/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from ckeditor_uploader.fields import RichTextUploadingField # ckeditor是一个富文本编辑器，将博客的content字段替换为RichTextField
from read_statistics.models import ReadNumExpandMethod # 导入计数统计类，让模型类继承此类
from read_statistics.models import ReadDetail
# from django.contrib.auth.models import User


# 博客类型
class BlogType(models.Model):
    type_name = models.CharField(max_length=15)

    def __str__(self):
        return self.type_name

    class Meta:
        db_table = 'blog_type'
        ordering = ['id']


# 博客
class Blog(models.Model, ReadNumExpandMethod):
    title = models.CharField(max_length=50)
    content =RichTextUploadingField()
    blog_type = models.ForeignKey('BlogType', on_delete=models.CASCADE)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add=True)
    last_updated_time = models.DateTimeField(auto_now=True)
    isdeleted = models.BooleanField(blank=True, default=False)
    read_detail = GenericRelation(ReadDetail)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'blog'
        ordering = ['-id']

blog/views.py
import logging

from django.shortcuts import render, get_object_or_404
from django.conf import settings
from django.core.paginator import Paginator  # 分页功能
from django.contrib.contenttypes.models import ContentType
from django.db.models import Count
from .models import BlogType, Blog
from read_statistics.utils import response_cookie_key
from comment.models import Comment
from comment.forms import CommentForm


logger = logging.getLogger('console')

def get_blog_list_common_data(request, blogs):
    '''获取博客列表共同数据'''
    # 使用分页器对象对博客进行分页，每页显示10条博客，page变量为Paginator的实例对象
    page = Paginator(blogs, settings.EACH_PAGE_BLOGS_NUMBER)
    current_page = request.GET.get('page', 1) # 取出url的page参数
    page_obj = page.get_page(current_page) # page_obj变量是某一页面的具体博客信息对象
    page_num = page_obj.number # 获取当前页的页码 
    # 根据页码来重新生成一个遍历列表，取当前页面+2与-2页：例[1,2,current_page=3,4,5]
    page_list = list(range(max(page_num-2, 1), min(page_num+3, page.num_pages+1)))
    # 添加省略号，例[1,...,5,6,7,8,9,...,12]
    if page_list[0]-2 >= 1:
        page_list.insert(0, '...')
    if page.num_pages - page_list[-1] >= 2:
        page_list.append('...')
    # 页面列表首值与尾值不等于1，总页码值时分别添加1与总页码值，达到[1,2,3,current_page=4,5,6,page.num_pages=12]效果
    if page_list[0] != 1:
        page_list.insert(0, 1)
    if page_list[-1] != page.num_pages:
        page_list.append(page.num_pages)
    # 获取博客所有的分类，并使用annotate备注添加实例属性blog_count，统计各分类有多少篇博客
    blog_types = BlogType.objects.annotate(blog_count=Count('blog'))
    # 按照年月进行日期的分类归档，并统计每个月有多少篇博客
    blog_dates = Blog.objects.dates('created_time', 'month', 'DESC') 
    blog_dates_dict = {}
    for blog_date in blog_dates:
        blog_dates_dict[blog_date] = Blog.objects.filter(created_time__year=blog_date.year, 
            created_time__month=blog_date.month).count()
    content = {
        'page_obj': page_obj, 'page_list': page_list, 
        'blogs': page_obj.object_list, 'blog_types': blog_types,
        'blog_dates_dict': blog_dates_dict
    }
    return content

def blog_list(request):
    '''博客展示列表'''
    blogs = Blog.objects.all() 
    content = get_blog_list_common_data(request, blogs)
    return render(request, 'blog/blog_list.html', content)


def blogs_with_type(request, blog_type_pk):
    '''博客分类'''
    # 查询博客分类，pk为参数blog_type_pk，得到此对象，如没有引发404异常
    blog_type = get_object_or_404(BlogType, pk=blog_type_pk)
    # 查询博客，条件：分类为blog_type对象，可能会有多条数据，所以使用filter
    blogs = Blog.objects.filter(blog_type=blog_type.pk)
    content = get_blog_list_common_data(request, blogs)
    content['blog_type'] = blog_type
    return render(request, 'blog/blogs_with_type.html', content)


def blogs_with_date(request, year, month):
    # 查询博客，条件：分类为blog_type对象，可能会有多条数据，所以使用filter
    blogs = Blog.objects.filter(created_time__year=year, created_time__month=month)
    content = get_blog_list_common_data(request, blogs)
    content['blog_date_sort'] = '%s年%s月' %(year, month)
    return render(request, 'blog/blogs_with_date.html', content)


def blog_detail(request, blog_pk):
    '''博客详细内容'''
    # 相当于使用Blog.objects.get(pk=blog_pk)，区别是如果查询不到则触发404异常
    blog = get_object_or_404(Blog, pk=blog_pk)
    # ct = ContentType.objects.get_for_model(blog)
    # comment_obj = Comment.objects.filter(content_type=ct, object_id=blog.pk, parent=None)
    blog_previous = Blog.objects.filter(pk__gt=blog.pk).last()
    blog_next = Blog.objects.filter(pk__lt=blog_pk).first()
    content = {
        'blog': blog, 'blog_previous': blog_previous, 
        'blog_next': blog_next
    }
    # 阅读计数判定要求为：访客浏览时只要浏览器不关闭那么重复访问某一篇博客时 阅读计数不重复增加
    key = response_cookie_key(request, blog)
    response = render(request, 'blog/blog_detail.html', content)
    # 得到cookie键，设置cookie，时间为浏览器关闭就失效
    response.set_cookie(key, 'true')
    return response

templates/blog/blog_detail.html
{% extends 'base.html'%}
{% block title %}{{ blog.title }}{% endblock title %}

{% load staticfiles %}
{% load comment_tags %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/blog.css' %}">
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/blog_detail.js' %}"></script>
{% endblock head %}

{% block blog_active %}active{% endblock blog_active %}

{% block body_two %}
    <div class="container">
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1">
                <h3>{{ blog.title}}</h3>
                <ul class="blog-info-description">
                    <li><span class="glyphicon glyphicon-user">{{ blog.author}}</span></li>
                    <li>
                        <span class="glyphicon glyphicon-tags">
                            <a href="{% url 'blog:blogs_with_type' blog.blog_type.pk %}">{{ blog.blog_type}}</a>
                        </span>
                    </li>
                    <li><span class="glyphicon glyphicon-time">{{ blog.created_time|date:"Y-m-d"}}</span></li>
                    <li><span>阅读({{ blog.get_read_num }})</span></li>
                    <li><span>评论({% get_comment_count blog %})</span></li>
                </ul>
                <div class="blog-content">
                    <p>{{ blog.content|safe}}</p>
                </div>
                <!--
                <div class="like">
                    <span class="glyphicon glyphicon-thumbs-up"></span>
                    <span class="liked_num">0</span>
                </div> -->
                <div class="blog-more">
                    {% if blog_previous %}
                        <p>上一篇：<a href="{% url 'blog:blog_detail' blog_previous.pk %}">{{ blog_previous }}</a></p>
                    {% else %}
                        <p>上一篇：已是最新博客</p>
                    {% endif %}
                    {% if blog_next %}
                        <p>下一篇：<a href="{% url 'blog:blog_detail' blog_next.pk %}">{{ blog_next }}</a></p>
                    {% else %}
                        <p>下一篇：这是最后一篇博客啦</p>
                    {% endif %}     
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1">
                <div class="comment">
                    <h3 class="comment-title">提交评论</h3>
                    {% if user.is_authenticated %}
                        <form id="comment-form" method="POST" style="overflow: hidden">
                            {% csrf_token %}
                            <label>{{ user.get_nickname_or_username }} 欢迎评论</label>
                            <div id="reply_content_container" style="display: none">
                                <p id="reply_title">回复</p>
                                <div id="reply_content"></div>
                            </div>
                                {% init_comment_form blog as CommentForm %}
                                {{ CommentForm }}
                            <span id="comment_error" class="text-danger pull-left"></span>
                            <input type="submit" class="btn btn-primary pull-right" value="评论">
                        </form>
                    {% else %}
                        <div>
                            <span>您还未登录，登录后方可评论~</span>
                            <a class="btn btn-primary" href="{% url 'user:sign_in' %}?form={{request.get_full_path}}">登录</a>
                            <span>or</span>
                            <a class="btn btn-danger" href="{% url 'user:sign_up' %}?form={{request.get_full_path}}">注册</a>
                        </div>
                    {% endif %}
                </div>
                <div class="comment">
                    <h3 class="comment-title">评论列表</h3>
                    <div id="comment_list">
                        {% get_comment_obj_list blog as comment_obj %}
                        {% for comment in comment_obj %}
                            <div class="comment" id="{{ comment.pk }}">
                                <span>{{ comment.user.get_nickname_or_username }}</span>
                                <span>({{ comment.comment_time|date:'Y-m-d H:i:s' }})</span>
                                <span class="comment-text">{{ comment.text|safe }}</span>
                                <button class="btn btn-primary reply_pk">回复</button>

                                {% for reply in comment.root_comment.all %}
                                    <div class="reply", id="{{ reply.pk }}">
                                        <span>{{ reply.user.get_nickname_or_username }}</span>
                                        <span>({{ reply.comment_time|date:'Y-m-d H:i:s' }})</span>
                                        <span>回复</span>
                                        <span>{{ reply.reply_to.get_nickname_or_username }}:</span>
                                        <span class="reply-text">{{ reply.text|safe }}</span>
                                        <button class="btn btn-primary reply_pk">回复</button>
                                    </div>
                                {% endfor %}
                            </div>
                        {% empty %}
                            <span id="no_comment">暂无评论</span>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body_two %}

templates/blog/blog_list.html
{% extends 'base.html' %}
{% block title %}博客列表{% endblock title %}

{% load staticfiles %}
{% load comment_tags %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/blog.css' %}">
{% endblock head %}

{% block blog_active %}active{% endblock blog_active %}
{# 页面内容 #}
{% block body_two %}    
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-md-9 col-lg-10">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        {% block blog_list_title %}博客列表{% endblock blog_list_title %}
                    </div>
                    <div class="panel-body"> 
                        {% for blog in blogs %}
                            <div class="blog">
                                <h3> <a href="{% url 'blog:blog_detail' blog.pk%}">{{ blog.title }}</a></h3>
                                <span class="glyphicon glyphicon-tags">
                                    <a href="{% url 'blog:blogs_with_type' blog.blog_type.pk %}">{{ blog.blog_type }}</a>
                                </span>
                                <span class="glyphicon glyphicon-time">{{ blog.created_time|date:'Y-m-d' }}</span>
                                <span>阅读({{ blog.get_read_num }})</span>
                                <span>评论({% get_comment_count blog %})</span>
                                <!-- <p>{{ blog.content|truncatechars:30|striptags }}</p> -->
                            </div>
                        {% empty %}
                            <div class="blog">
                                <h3>暂无博客，请期待!</h3>
                            </div>
                        {% endfor %}  
                    </div>
                </div>
                <div class="paginator">
                    <ul class="pagination">
                        {# 上一页 #}
                        <li>
                            {% if page_obj.has_previous %}
                                <a href="?page={{ page_obj.previous_page_number}}" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            {% else %}
                                <span aria-hidden="true">&laquo;</span>
                            {% endif %}
                        </li>
                        {# 全部页 #}
                        {% for current_page in page_list %}
                            {# 将当前页设置为高亮显示 #}
                            {% if current_page == page_obj.number %}
                                <li class="active"><span>{{ current_page }}</span></li>
                            {% else %}
                                {% if current_page == '...' %}
                                     <li><span>{{ current_page }}</span></li>
                                {% else %}
                                    <li><a href="?page={{current_page}}">{{ current_page }}</a></li>
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                        {# 下一页 #}
                        <li>
                            {% if page_obj.has_next %}
                                <a href="?page={{ page_obj.next_page_number}}" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            {% else %}
                                <span aria-hidden="true">&raquo;</span>
                            {% endif %}
                        </li>
                    </ul>
                    <p>
                        共有{{ page_obj.paginator.count}}篇博客, 当前第{{ page_obj.number }}页, 共{{ page_obj.paginator.num_pages }}页
                    </p>
                </div>
            </div>    
            <div class="hidden-xs col-sm-4 col-md-3 col-lg-2">
                <div class="panel panel-default">
                    <div class="panel-heading">博客分类</div>
                    <div class="panel-body">
                        <ul class="blog-types">
                        {% for blog_type in blog_types %}
                            <li>
                                <a href="{% url 'blog:blogs_with_type' blog_type.pk %}">
                                    {{ blog_type.type_name }}({{blog_type.blog_count}})
                                </a>
                            </li>
                        {% empty %}
                            <li>暂无分类</li>
                        {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">日期归档</div>
                    <div class="panel-body">
                        <ul class="blog-types">
                            {% for blog_date, blog_count in blog_dates_dict.items %}
                                <li>
                                    <a href="{% url 'blog:blogs_with_date' blog_date.year blog_date.month %}">
                                        {{ blog_date|date:'Y年m月' }}({{blog_count}})
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>      
        </div>
    </div>
{% endblock body_two %}

templates/blog/blogs_with_date.html
{% extends 'blog/blog_list.html'%}

{% block blog_list_title %}
    日期归档：{{ blog_date_sort }} <a href="{% url 'blog:blog_list' %}">查看全部博客</a>
{% endblock blog_list_title %}

templates/blog/blogs_with_type.html
{% extends 'blog/blog_list.html'%}

{% block blog_list_title %}
    分类：{{ blog_type.type_name }} <a href="{% url 'blog:blog_list' %}">查看全部博客</a>
{% endblock blog_list_title %}