blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    # http://localhost:8000/blog?page=1  进入博客列表,默认进入第一页
    path('', views.blog_list, name = 'blog_list'),
    # http://localhost:8000/blog/博客的id值  进入博客详情页面
    path('<int:blog_pk>', views.blog_detail, name = 'blog_detail'),
    # http://localhost:8000/blog/type/博客分类的id 按照博客分类对博客进行分类
    path('type/<int:blog_type_pk>', views.blogs_with_type, name = 'blogs_with_type'),
    # http://localhost:8000/blog/date/年/月 按照年月对博客进行归档
    path('date/<int:year>/<int:month>', views.blogs_with_date, name = 'blogs_with_date'),
]

mysite/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('user/', include('user.urls', namespace='user')),
    # path('signin/', views.sign_in, name='sign_in'),
    # path('signup/', views.sign_up, name='sign_up'),   
    path('comment/', include('comment.urls', namespace='comment')),  
    path('likes/', include('likes.urls', namespace='likes')),
]
# ckeditor富文本编辑器访问图片指定路径
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('signin/', views.sign_in, name='sign_in'),
    path('signup/', views.sign_up, name='sign_up'),
    path('signout/', views.sign_out, name='sign_out'),
    path('user_info/', views.user_info, name='user_info'),
    path('nickname_change/', views.nickname_change, name='nickname_change'),
    path('bind_email/', views.bind_email, name='bind_email'),
    path('send_verification_code/', views.send_verification_code, name='send_verification_code'),
]

templates/base.html
{% load staticfiles %} <!-- 加载...看说明 -->
<!DOCTYPE html>
<html lang="zh-CN">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock title %}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
        <link href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">
        <script type="text/javascript" src="{% static 'js/jquery.1.12.4.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
        {% block head %}{% endblock head %}
    </head>
    <body>
    {% block body%}
        <nav class="navbar navbar-default"> <!-- 制作导航条，使用nav标签 -->
            <div class="container-fluid"> <!-- 还可包含一个.container或.container-fluid容器，从而让导航条居中，并在两侧添加内补(padding） -->
                <div class="navbar-header"> <!-- 向<div>元素添加一个标题.navbar-header，内部包含了带有.navbar-brand的元素。这会让文本看起来更大一号 -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"aria-expanded="false"> <!-- 为了给导航栏添加响应式特性，需要折叠的内容必须包裹在带有.collapse，.navbar-collapse的<div> 中。折叠起来的导航栏实际上是一个带有.navbar-toggle及两个data-元素的按钮。第一个是data-toggle，用于告诉JavaScript需要对按钮做什么，第二个是 data-target，指示要切换到哪一个元素。三个带有.icon-bar 的 <span> 创建所谓的汉堡按钮。这些会切换为 .nav-collapse <div> 中的元素。为了实现以上这些功能，必须包含 Bootstrap 折叠（Collapse）插件 -->
                        <span class="sr-only">切换导航</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <div class="navbar-brand">个人博客网站</div>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                   <ul class="nav navbar-nav"> <!-- 为了向导航栏添加链接，只需要简单地添加带有.nav，.navbar-nav 的无序列表即可 -->
                        <li class="{% block index_active %}{% endblock index_active %}"> 
                            <a href="{% url 'home' %}">首页</a>
                        </li>
                        <li class="{% block blog_active %}{% endblock blog_active %}">
                            <a href="{% url 'blog:blog_list' %}">博客</a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if not user.is_authenticated %}
                            <li><a href="{% url 'user:sign_in' %}?form={{ request.get_full_path }}">登录</a></li>
                            <li><a href="{% url 'user:sign_up' %}?form={{ request.get_full_path }}">注册</a></li>
                        {% else %}
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">
                                    {% if user.has_nickname %}
                                        {{ user.username }}({{ user.get_nickname }})
                                    {% else%}
                                        {{ user.username }}
                                    {% endif %}
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="{% url 'user:user_info' %}?form={{ request.get_full_path }}">个人资料</a></li>
                                    <li><a href="{% url 'admin:index' %}">后台管理</a></li>
                                    <li><a href="{% url 'user:sign_out' %}?form={{ request.get_full_path }}">登出</a></li>
                              </ul>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        {% block body_two %}{% endblock body_two %}
    {% endblock body %}
    </body>
</html>

templates/error.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}我的网站{% endblock title %}

{% block index_active %}active{% endblock index_active %}

{% block body_two %}
    {{ error_message }} <a href="{{ referer }}">返回</a>
{% endblock body_two %}

templates/form.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}{{ page_title }}{% endblock title %}

{% block head %}
    <script type="text/javascript" src="{% static 'js/user.js' %}"></script>
{% endblock head %}

{% block index_active %}active{% endblock index_active %}

{% block body_two %}
    <div class="container">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">{{ page_title }}</h3>
                    </div>
                    <div class="panel-body">
                         <form action="" method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                {% if not field.is_hidden %}
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {% endif %}
                                {{ field }}
                                <p class="text-danger">{{ field.error.as_text }}</p>
                            {% endfor %}
                            <span class="text-danger" id="tip">{{ form.non_field_errors }}</span>
                            <div class="clearfix"></div>
                            <div class="pull-left">
                                {% block form_content %}{% endblock form_content %}
                            </div>
                            <button type="submit" class="btn btn-primary pull-right">{{ submit_text }}</button>
                            <button type="submit" class="btn btn-default pull-right" onclick="window.location.href='{{ redirect_to }}'"">返回
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body_two %}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}我的网站{% endblock title %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
    <script src="http://cdn.highcharts.com.cn/highcharts/highcharts.js"></script>
{% endblock head %}
{% block index_active %}active{% endblock index_active %}

{% block body_two %}
    <h3 class="logo">欢迎访问我的网站</h3>
    <!--使用了highchart图表 官网：https://www.highcharts.com.cn -->
    <!-- 图表容器 DOM -->
    <div id="container"></div>
    <div class="hot-date">
        <h3>今日热门博客</h3>
        <ul>
            {% for today_hot_blog in today_hot_blogs %}
                <li>
                    <a href="{% url 'blog:blog_detail' today_hot_blog.object_id %}">{{ today_hot_blog.content_object.title }}</a>({{ today_hot_blog.read_num }})
                </li>
            {% empty %}
                <li>今日暂无热门博客</li>
            {% endfor %}
        </ul>
    </div>
    <div class="hot-date">
        <h3>昨日热门博客</h3>
        <ul>
            {% for yesterday_hot_blog in yesterday_hot_blogs %}
                <li>
                    <a href="{% url 'blog:blog_detail' yesterday_hot_blog.object_id %}">{{ yesterday_hot_blog.content_object.title }}</a>({{ yesterday_hot_blog.read_num }})
                </li>
            {% empty %}
                <li>昨日暂无热门博客</li>
            {% endfor %}
        </ul>
    </div>
    <div class="hot-date">
        <h3>最近7天热门博客</h3>
        <ul>
            {% for seven_hot_blog in seven_hot_blogs %}
                <li>
                    <a href="{% url 'blog:blog_detail' seven_hot_blog.id %}">{{ seven_hot_blog.title }}</a>({{ seven_hot_blog.read_num_sum }})
                </li>
            {% empty %}
                <li>暂无热门博客</li>
            {% endfor %}
        </ul>
    </div>
    <script>
        // 图表配置
        var options = {
            chart: {
                type: 'line'                          //指定图表的类型，默认是折线图（line）
            },
            title: {
                text: null                 // 标题
            },
            xAxis: {
                categories: {{ dates|safe }},   // 
                tickmarkPlacement: 'on',
                title: { text: '前7日阅读量变化' },
            },
            yAxis: {
                title: {
                    text: null                // y 轴标题
                },
                labels: { enabled: false },
                gridLineDashStyle: 'Dash',
            },
            series: [{                              // 数据列
                name: '阅读量',                        // 数据列名
                data: {{ read_nums }}                    // 数据    [1,2,3,4,5,6,7
            }],
            plotOptions: {
            	line: {
            		dataLabels: {
            			enabled: true
            		}
            	}
            },
            legend: {enabled: false},
            credits: {enabled: false},
        };
        // 图表初始化函数
        var chart = Highcharts.chart('container', options);
    </script>
{% endblock body_two %}