blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    # http://localhost:8000/blog?page=1  进入博客列表,默认进入第一页
    path('', views.blog_list, name = 'blog_list'),
    # http://localhost:8000/blog/博客的id值  进入博客详情页面
    path('<int:blog_pk>', views.blog_detail, name = 'blog_detail'),
    # http://localhost:8000/blog/type/博客分类的id 按照博客分类对博客进行分类
    path('type/<int:blog_type_pk>', views.blogs_with_type, name = 'blogs_with_type'),
    # http://localhost:8000/blog/date/年/月 按照年月对博客进行归档
    path('date/<int:year>/<int:month>', views.blogs_with_date, name = 'blogs_with_date'),
]

mysite/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('user/', include('user.urls', namespace='user')),
    # path('signin/', views.sign_in, name='sign_in'),
    # path('signup/', views.sign_up, name='sign_up'),   
    path('comment/', include('comment.urls', namespace='comment')),  
    path('likes/', include('likes.urls', namespace='likes')),
]
# ckeditor富文本编辑器访问图片指定路径
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('signin/', views.sign_in, name='sign_in'),
    path('signup/', views.sign_up, name='sign_up'),
    path('signout/', views.sign_out, name='sign_out'),
    path('user_info/', views.user_info, name='user_info'),
    path('nickname_change/', views.nickname_change, name='nickname_change'),
    path('bind_email/', views.bind_email, name='bind_email'),
    path('send_verification_code/', views.send_verification_code, name='send_verification_code'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=20, verbose_name='昵称')

    def __str__(self):
        return self.user.username

    class Meta:
        db_table = 'profile'


# 动态绑定User类实例,判断登录用户是否有昵称
def get_nickname(self):
    if Profile.objects.filter(user=self).exists():
        return Profile.objects.get(user=self).nickname
    else:
        return ''

def get_nickname_or_username(self):
    if Profile.objects.filter(user=self).exists():
        return Profile.objects.get(user=self).nickname
    else:
        return self.username

def has_nickname(self):
    return Profile.objects.filter(user=self).exists()

User.get_nickname = get_nickname
User.get_nickname_or_username = get_nickname_or_username
User.has_nickname = has_nickname

user/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User


class SignInForm(forms.Form):
    username = forms.CharField(
        label='用户名', 
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': '请输入用户名'}
        )
    )
    password = forms.CharField(
        label='密码', 
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': '请输入密码'}
        )
    )
    # 当执行form.is_valid()时，例如【if sign_in_form.is_valid():】,会对每个field进行检查，并立即产生cleaned_data的数据，
    # 如果有clean或clean_开头的方法，则开始执行此函数(此时cleaned_data的数据已经可以用了)
    # 因为字段数据已经被指定字段的默认校验逻辑执行完毕了，说明校验通过，cleaned_data就会有数据，同样，我们不必担心数据是否为空，因为它已经被校验过了
    # 注意：如果校验不通过不会执行clean或clean_开头的方法
    def clean(self):
        # 数据已经合法，进行提取
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        # 验证此用户
        user = authenticate(username=username, password=password)
        # 不存在，抛出异常
        if user is None:
            print('xxx')
            raise forms.ValidationError('用户名或密码不正确')
        # 反之添加user用户并返回
        else:
            self.cleaned_data['user'] = user
        print('xxxxxx')
        return self.cleaned_data


class SignUpForm(forms.Form):
    username = forms.CharField(
        label='用户名', 
        max_length='30',
        min_length='3',
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': '请输入用户名'}
        )
    )
    email = forms.CharField(
        label='邮箱', 
        widget=forms.EmailInput(
            attrs={'class': 'form-control', 'placeholder': '请输入邮箱'}
        )
    )
    password = forms.CharField(
        label='密码', 
        min_length='6', 
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': '请输入密码'}
        )
    )
    password_again = forms.CharField(
        label='再次输入密码', 
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': '请再次输入密码'}
        )
    )
    
    def clean(self):
        username = self.cleaned_data.get('username')
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        password_again = self.cleaned_data.get('password_again')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('用户名已存在')

        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('邮箱已存在')

        if password != password_again:
            raise forms.ValidationError('密码不一致')
        return self.cleaned_data


class NicknameChangeForm(forms.Form):
    nickname_new = forms.CharField(
        label='新的昵称', 
        max_length=20, 
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': '请输入新的昵称'}
        )
    )

    def __init__(self, *args, **kwargs):
        if 'user' in kwargs:
            self.user = kwargs.pop('user')
        super().__init__(*args, **kwargs)

    def clean(self):
        if self.user.is_authenticated:
            self.cleaned_data['user'] = self.user
        else:
            raise forms.ValidationError('用户未登录')
        nickname_new = self.cleaned_data.get('nickname_new', '').strip()
        if nickname_new == '':
            raise forms.ValidationError('昵称不能为空')
        return self.cleaned_data

class BindEmailForm(forms.Form):
    email = forms.EmailField(
        label='邮箱',
        widget=forms.EmailInput(
            attrs={'class': 'form-control', 'placeholder': '请输入邮箱'}
        )
    )
    verification_code = forms.CharField(
        label='验证码',
        required=False,
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': '请发送验证码到邮箱'}
        )
    )

    def __init__(self, *args, **kwargs):
        if 'request' in kwargs:
            self.request = kwargs.pop('request')
        super().__init__(*args, **kwargs)

    def clean(self):
        if self.request.user.is_authenticated:
            self.cleaned_data['user'] = self.request.user
        else:
            raise forms.ValidationError('用户未登录')
        # 判断此用户是否已绑定邮箱
        if self.request.user.email != '':
            raise forms.ValidationError('您已经绑定邮箱')
        # 判断邮箱
        email = self.cleaned_data.get('email', '').strip()
        if email == '':
            raise forms.ValidationError('邮箱不能为空')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('该邮箱已经被绑定')
        # 判断验证码
        code = self.request.session.get('bind_email_code', '')
        verification_code = self.cleaned_data.get('verification_code', '')
        print(code)
        if not (code != '' and code == verification_code):
            raise forms.ValidationError('验证码不正确')
        return self.cleaned_data


    

user/views.py
import string
import random
import time
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.contenttypes.models import ContentType
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from django.urls import reverse
from django.http import JsonResponse
from blog.models import Blog
from .forms import SignInForm, SignUpForm, NicknameChangeForm, BindEmailForm
from .models import Profile


# 登录处理
def sign_in(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request 创建一个表单实例并用来自请求的数据填充它:
        sign_in_form = SignInForm(request.POST)
        # check whether it's valid 检查它是否有效:
        if sign_in_form.is_valid():
            # 存在则提取用户信息
            user = sign_in_form.cleaned_data.get('user')
            # 用户存在则使用login()进行登录
            login(request, user)
            return redirect(request.GET.get('form', reverse('home')))
    else:
        sign_in_form = SignInForm()
    content = {
        'sign_in_form': sign_in_form
    }
    return render(request, 'user/sign_in.html', content)


# 注册处理
def sign_up(request):
    if request.method == 'POST':
        sign_up_form = SignUpForm(request.POST)
        if sign_up_form.is_valid():
            username = sign_up_form.cleaned_data.get('username')
            email = sign_up_form.cleaned_data.get('email')
            password = sign_up_form.cleaned_data.get('password')
            # 创建用户，内置User保存密码时需要加密，调用set_password方法即可
            user = User.objects.create_user(username, email, password)
            user.save()
            # 登录
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect(request.GET.get('form'), reverse('home'))
    else:
        sign_up_form = SignUpForm()
    content = {
        'sign_up_form': sign_up_form
    }
    return render(request, 'user/sign_up.html', content)

# 登出处理
def sign_out(request):
    logout(request)
    return redirect(request.GET.get('form'), reverse('home'))

# 个人资料展示
def user_info(request):
    return render(request, 'user/user_info.html')

# 修改昵称
def nickname_change(request):
    redirect_to = request.GET.get('form', reverse('home'))
    if request.method == 'POST':
        nickname_change_form = NicknameChangeForm(request.POST, user=request.user)
        if nickname_change_form.is_valid():
            nickname_new = nickname_change_form.cleaned_data['nickname_new']
            profile_obj, created = Profile.objects.get_or_create(user=request.user)
            profile_obj.nickname = nickname_new
            profile_obj.save()
            return redirect(redirect_to)
    else:
        nickname_change_form = NicknameChangeForm()
    content = {
        'page_title': '修改昵称', 'form': nickname_change_form,
        'submit_text': '修改', 'redirect_to': redirect_to
    }
    return render(request, 'form.html', content)

# 绑定邮箱
def bind_email(request):
    redirect_to = request.GET.get('form', reverse('home'))
    if request.method == 'POST':
        bind_email_form = BindEmailForm(request.POST, request=request)
        if bind_email_form.is_valid():
            email = bind_email_form.cleaned_data['email']
            request.user.email = email
            request.user.save()
            return redirect(redirect_to)
    else:
        bind_email_form = BindEmailForm()
    content = {
        'page_title': '绑定邮箱', 'form': bind_email_form,
        'submit_text': '绑定', 'redirect_to': redirect_to
    }
    return render(request, 'user/verification_code.html', content)

# 发送验证码
def send_verification_code(request):
    email = request.GET.get('email')
    data = {}
    if email != '':
        # 生成验证码
        code = ''.join(random.sample(string.ascii_letters + string.digits, 4))
        now = int(time.time())
        send_code_time = request.session.get('send_code_time', 0)
        if now - send_code_time < 60:
            data['status'] = 'ERROR'
        else:
            request.session['bind_email_code'] = code
            request.session['send_code_time'] = now
            # 发送验证码邮件
            send_mail(
                '绑定邮箱',
                '验证码： %s' % code,
                '443936974@qq.com',
                [email],
                fail_silently=False,
            )
            data['status'] = 'SUCCESS'
    else:
        data['status'] = 'ERROR'
    return JsonResponse(data)

templates/user/sign_in.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}我的网站{% endblock title %}

{% block index_active %}active{% endblock index_active %}

{% block body_two %}
    <div class="container">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                {% if not user.is_authenticated %}
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">登录</h3>
                        </div>
                        <div class="panel-body">
                             <form action="" method="POST">
                                {% csrf_token %}
                                {% for field in sign_in_form %}
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                    {{ field }}
                                    <p class="text-danger">{{ field.error.as_text }}</p>
                                {% endfor %}
                                <span class="pull-left text-danger">{{ sign_in_form.non_field_errors }}</span>
                                <button type="submit" class="btn btn-primary pull-right">登录</button>
                            </form>
                        </div>
                    </div>
                {% else %}
                    <span>未登录，跳转到首页...</span>
                    <script type="text/javascript">
                        window.location.href='/';
                    </script>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock body_two %}

templates/user/sign_up.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}我的网站{% endblock title %}

{% block index_active %}active{% endblock index_active %}

{% block body_two %}
    <div class="container">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                {% if not user.is_authenticated %}
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">注册</h3>
                        </div>
                        <div class="panel-body">
                             <form action="" method="POST">
                                {% csrf_token %}
                                {% for field in sign_up_form %}
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                    {{ field }}
                                    <p class="text-danger">{{ field.error.as_text }}</p>
                                {% endfor %}
                                <span class="pull-left text-danger">{{ sign_up_form.non_field_errors }}</span>
                                <button type="submit" class="btn btn-primary pull-right">注册</button>
                            </form>
                        </div>
                    </div>
                {% else %}
                    <span>未登录，跳转到首页...</span>
                    <script type="text/javascript">
                        window.location.href='/';
                    </script>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock body_two %}

templates/user/user_info.html
{% extends 'base.html' %}
{% block title %}个人资料{% endblock title %}

{% block index_active %}active{% endblock index_active %}

{% block body_two %}
    <div class="container">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                {% if user.is_authenticated %}
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">个人资料</h3>
                        </div>
                        <div class="panel-body">
                            <ul>
                                <li>昵称：{{ user.get_nickname }} 
                                    <a href="{% url 'user:nickname_change' %}?form={{ request.get_full_path }}">修改昵称</a>
                                </li>
                                <li>邮箱：{% if user.email %}{{ user.email }}{% else %}未绑定 
                                    <a href="{% url 'user:bind_email' %}?form={{ request.get_full_path }}">绑定邮箱</a>{% endif %}
                                </li>
                                <li>上次登录时间:{{ user.last_login|date:"Y-m-d H:i:s" }}</li>
                                <li><a href="">修改密码:</a></li>
                            </ul>
                        </div>
                    </div>
                {% else %}
                    <span>未登录，跳转到首页...</span>
                    <script type="text/javascript">
                        window.location.href='/';
                    </script>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock body_two %}

templates/user/verification_code.html
{% extends 'form.html' %}
{% block form_content %}
    <button type="button" class="btn btn-primary" id="code">发送验证码</button>
{% endblock form_content %}